### ISSUE TITLE
Fix Hostname  in User_validation

### ISSUE THREAD

**Issue by robertej-phd** [mit-mc-clas12/client#1]
hostname -d doesn't work on Mac.
In principle, the following should work:
hostname -f | sed -e 's/^[^.]*\.//'

This (or some equivalent that works on ~ all machines [or throws an error/warning that is workable]) needs to be implemented properly. Also; should have a formal solution for when testing on Travis CI

**Comment by maureeungaro** [comment]
Added domain.sh in the utlis repo. Works on Linux and Darwin.
